import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import {
  BrainCircuit,
  Check,
  Lightbulb,
  ShieldCheck,
  TrendingUp,
  X,
} from "lucide-react";
import {
  BarChart,
  Bar,
  ResponsiveContainer,
  XAxis,
  YAxis,
  Tooltip,
} from "recharts";
import api from "../../services/api";
import {
  EmptyState,
  ErrorState,
  Loading,
} from "../../components/common/States";
export function ResumeAnalysis() {
  const { id } = useParams();
  const [analysis, setAnalysis] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  useEffect(() => {
    api
      .get(`/api/resume/${id}/analysis`)
      .then(({ data }) => setAnalysis(data.analysis))
      .catch((err) =>
        setError(
          err.response?.data?.message || "Unable to fetch resume analysis",
        ),
      )
      .finally(() => setLoading(false));
  }, [id]);
  if (loading) return <Loading label="Loading analysis" />;
  if (error)
    return error === "Resume analysis not found" ? (
      <EmptyState
        title="Analysis not ready yet."
        description="Analyze this resume first, then your preparation signals will appear here."
      />
    ) : (
      <ErrorState message={error} />
    );
  if (!analysis)
    return (
      <EmptyState
        title="No analysis available."
        description="There is no saved analysis for this resume yet."
      />
    );
  const chartData = [{ name: "Score", value: analysis.overallScore }];
  return (
    <>
      <div className="page-heading analysis-heading">
        <div>
          <span className="eyebrow">
            <BrainCircuit size={14} /> AI resume analysis
          </span>
          <h1>Your resume, decoded.</h1>
          <p>A clear read on what is working and where to focus next.</p>
        </div>
        <span className="model-badge">{analysis.model}</span>
      </div>
      <section className="analysis-top">
        <div className="score-card">
          <div>
            <span className="eyebrow">Overall score</span>
            <strong>
              {analysis.overallScore}
              <small>/100</small>
            </strong>
            <span className="score-note">
              <TrendingUp size={15} /> Your starting point
            </span>
          </div>
          <div className="analysis-chart">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={chartData}>
                <XAxis dataKey="name" hide />
                <YAxis domain={[0, 100]} hide />
                <Tooltip cursor={false} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
        <div className="content-panel summary-card">
          <span className="eyebrow">Executive summary</span>
          <h2>{analysis.summary}</h2>
          <p>Generated by {analysis.model} and saved to your workspace.</p>
        </div>
      </section>
      <div className="analysis-grid">
        <AnalysisList
          title="Strengths"
          icon={Check}
          items={analysis.strengths}
          tone="positive"
        />
        <AnalysisList
          title="Weaknesses"
          icon={X}
          items={analysis.weaknesses}
          tone="negative"
        />
        <AnalysisList
          title="Missing skills"
          icon={Lightbulb}
          items={analysis.missingSkills}
          tone="warning"
        />
        <AnalysisList
          title="Suggestions"
          icon={TrendingUp}
          items={analysis.suggestions}
          tone="neutral"
        />
      </div>
      <section className="content-panel ats-panel">
        <div>
          <span className="eyebrow">
            <ShieldCheck size={14} /> ATS feedback
          </span>
          <h2>Make it easier to find you.</h2>
        </div>
        <p>{analysis.atsFeedback}</p>
      </section>
    </>
  );
}
function AnalysisList({ title, icon: Icon, items = [], tone }) {
  return (
    <article className={`analysis-list ${tone}`}>
      <div className="list-title">
        <span className="list-icon">
          <Icon size={16} />
        </span>
        <h3>{title}</h3>
        <span>{items.length}</span>
      </div>
      {items.length ? (
        <ul>
          {items.map((item) => (
            <li key={item}>{item}</li>
          ))}
        </ul>
      ) : (
        <p>No signals here yet.</p>
      )}
    </article>
  );
}
